version: 0.2

env:
  variables:
    TF_VERSION: "1.8.5"

phases:
  install:
    commands:
      - echo "Installing Terraform $TF_VERSION"
      - curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  build:
    commands:
      - echo "Starting Terraform build..."
      - terraform init -no-color
      - terraform plan --auto-approve

  post_build:
    commands:
      - echo "Resources created successfully!"
